# .github/workflows/build.yml

name: Windows-Build
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up MSVC environment
        uses: microsoft/setup-msbuild@v1.0.2
        with:
          msbuild-version: '16.0'
      - name: Install LLVM for Clang
        run: |
          choco install llvm -y
      - name: Build with Clang
        run: |
          mkdir build && cd build
          clang ../main.c -o my_app.exe
#          cmake -G "Ninja" -DCMAKE_C_COMPILER=clang.exe -DCMAKE_CXX_COMPILER=clang++.exe ..
#          cmake --build .
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release 1.0.0
          body: |
            Description of the release.
          draft: false
          prerelease: false
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build/my_app.exe
          asset_name: my_app.exe
          asset_content_type: application/octet-stream